version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "frontend"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      frontend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "backend"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      backend-dependencies:
        patterns:
          - "*"
