plugins {
    id("base")
}

def npmCommand = System.getProperty("os.name").toLowerCase().contains("windows") ? "npm.cmd" : "npm"

tasks.register("npmCi", Exec) {
    workingDir(projectDir)
    commandLine(npmCommand, "ci")
}

tasks.named("build") {
    dependsOn("npmCi")
    doLast {
        exec {
            workingDir(projectDir)
            commandLine(npmCommand, "run", "build")
        }
    }
}
